services:
  postgres:
    image: postgres:16
    container_name: multi_shop_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: multishop
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"

  api:
    build: .
    container_name: multi_shop_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
