services:
  postgres:
    image: postgres:16
    container_name: multi_shop_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: multishop
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: multi_shop_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./api/.env
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: multi_shop_frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:8080

volumes:
  pgdata:
